apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true' # need for wildcards in path names
spec:
  ingressClassName: nginx
  rules:
    - host: gittixlocal.com
    # - host: localhost
      http:
        paths:
          - path: /api/users/?(.*) # the route we are expecting requests on in api
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv # service name
                port:
                  number: 3000
          - path: /api/ticketing/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ticketing-srv
                port:
                  number: 3000
          - path: /?(.*) # has to go at end as catch-all
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv # service name
                port:
                  number: 3000

# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml